SunScreenApplication/Models/ErrorViewModel.cs
namespace SunScreenApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SunScreenApplication/Models/Location.cs
using Microsoft.EntityFrameworkCore;

namespace SunScreenApplication.Models
{
    public class Location
    {
        public int Id { get; set; }
        public string? Postcode { get; set; }
        public string? Suburb { get; set; }
        public string? State { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    }

    public class LocationDBContext : DbContext
    {
        public LocationDBContext(DbContextOptions<LocationDBContext> options) : base(options)
        {

        }

        public DbSet<Location> postcodes_geo { get; set; }
    }
}

SunScreenApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SunScreenApplication.Models;
using System.Diagnostics;

namespace SunScreenApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public ActionResult FunSunSafety()
        {
            ViewBag.Message = "Fun Sun Safety for Children page";

            return View();
        }

        public ActionResult SunscreenUsage()
        {
            ViewBag.Message = "Sunscreen Usage page";

            return View();
        }

        public ActionResult ClothingRecommendations()
        {
            ViewBag.Message = "Clothing Recommendations page";

            return View();
        }
    }
}

SunScreenApplication/Controllers/UvIndexController.cs
using Microsoft.AspNetCore.Mvc;
using SunScreenApplication.Models;
using System.Text.Json;

namespace SunScreenApplication.Controllers
{
    public class UvIndexController : Controller
    {
        private LocationDBContext _db;

        public UvIndexController(LocationDBContext db)
        {
            _db = db;
        }

        public IActionResult Form()
        {
            return View();
        }

        // POST: /UvIndex/Form
        [HttpPost]
        public async Task<IActionResult> Form(string postcode)
        {
            var location = _db.postcodes_geo.FirstOrDefault(l => l.Postcode == postcode);

            if (location != null)
            {
                decimal latitude = location.Latitude;
                decimal longitude = location.Longitude;

                // Call the web API with latitude and longitude values
                var response = await CallApi(latitude, longitude);

                // Check the result from the API and handle accordingly
                if (response.IsSuccessStatusCode)
                {
                    var contents = await response.Content.ReadAsStringAsync();
                    ViewBag.JsonContents = contents;

                    // If the API call is successful, return view
                    return View();
                }
                else
                {
                    // If the API call fails, handle the error
                    ModelState.AddModelError(string.Empty, "Failed to call the web API.");
                    return View();
                }
            }
            else
            {
                // Handle the case where no data is found for the provided postcode
                ModelState.AddModelError("PostcodeNotFound", "The provided postcode was not found in the database.");
                return View();
            }
        }

        private async Task<HttpResponseMessage> CallApi(decimal latitude, decimal longitude)
        {
            using (var client = new HttpClient())
            {
                // Construct the URL for the web API using latitude and longitude values
                string apiUrl = $"https://api.openweathermap.org/data/3.0/onecall?lat={latitude}&lon={longitude}&appid=8b600573654443eb01a6d8334d00efeb";

                // Make an HTTP GET request to the web API
                return await client.GetAsync(apiUrl);
            }
        }
    }
}

SunScreenApplication/Views/Home/ClothingRecommendations.cshtml
@{
    ViewBag.Title = "ClothingRecommendations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1.0" />


<!-- 2nd Section: Clothing Protection -->
<div id="ClothingProtectionStart"></div>
<div class="portionheader">
    <h1>What to Wear?</h1>
</div>
<p>
    Choosing the right clothing for high UV weather can be confusing and sometimes dangerous! Did you know that you can be burnt through certain fabrics? However, clothing is still the best way to protect your skin from sun damage according to the skin cancer foundation (Skin Cancer Foundation, 2019).
</p>
<p>
    Clothing is rated with an Ultraviolet Protection factor (UPF) that demonstrates how protective it is from the sun. A garment with a UPF of 50 allows only 2% of the sun’s rays to impact your skin thus providing a substantial barrier to damage and without the need to reapply (Skin Cancer Foundation, 2019).
</p>
<p>
    NOTE: this differs from the Sun Protection Factor which measures the time for your UV exposed skin to burn. For example, if you use SPF 15 correctly you can stay in the sun 15 times longer than without the sunscreen before you burn (Skin Cancer Foundation, 2019). Additionally, SPF only relates to levels of UVB radiation while UPF relates to both UVA and UVB radiation. Please see here (hyper link on here) for more information about UVA and UVB!
</p>
<p>
    Here are some general rules you can use when deciding on if a garment will protect you or not (all information sourced from the Skin Cancer Foundation (2019)):
</p>
<p>
    - Colour: yes colour! Darker fabrics absorb more light than lighter ones thus offering you more protection.
</p>
<p>
    - Make and material: how densely woven a garment is and what its constructed with all help determine its UPF. For instance, lightweight linen shirts can be so breathable they allow the sun in while dense materials such as denim can offer complete sun protection. Additionally, tight fabrics are generall.y less sun protective than loose ones.
</p>
<p>
    - UPF: some garments such as rash guards and outdoor wear may provide UPF labels and inform you about how protective the clothing is.
</p>
<p>
    - Activity: be aware that when a garment is wet or manipulated by sport or other activity its protection can be reduced!
</p>

<!-- Setup like a row by row format -->
<div class="uv-index-guide-vertical">

    <!-- Low -->
    <div class="stage-row">
        <div class="image-collage-wrap">
            <img src="https://images.pexels.com/photos/16285863/pexels-photo-16285863/free-photo-of-bearded-man-in-shirt-standing-on-wooden-bridge.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/4992628/pexels-photo-4992628.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/3838941/pexels-photo-3838941.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
        </div>
        <div class="text-section">
            <h4>Low UV Index: 1-2</h4>
            <p>Normal outdoor wear required. Add a hat and sunglasses as necessary. Very low risk for sunburn. No sunscreen required </p>
        </div>
    </div>

    <!-- Moderate -->
    <div class="stage-row">
        <div class="text-section">
            <h4>Moderate UV Index: 3-5</h4>
            <p>This is a moderate level of UV that requires exposed skin to be protected if outside for long periods of time. Wear a loose fitting, densely woven material that covers as much of the body as possible. Wear a hat. Wear SPF 15-10 depending on skin type and reapply every 2 hours.</p>
        </div>
        <div class="image-collage-wrap">
            <img src="https://images.pexels.com/photos/16354132/pexels-photo-16354132/free-photo-of-man-in-hat-and-shirt-standing-with-arms-crossed.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/8063404/pexels-photo-8063404.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/13250390/pexels-photo-13250390.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/1887975/pexels-photo-1887975.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
        </div>
    </div>

    <!-- High -->
    <div class="stage-row">
        <div class="image-collage-row">
            <img src="https://images.pexels.com/photos/5191436/pexels-photo-5191436.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/20411282/pexels-photo-20411282/free-photo-of-elderly-man-in-shirt-looking-at-seashore-in-portugal.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/9289896/pexels-photo-9289896.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Image for clothing section" />
        </div>
        <div class="text-section">
            <h4>High UV Index: 6-7</h4>
            <p>High risk of sun damage to unexposed skin. If outside for extended periods cover all exposed skin with densely woven and dark coloured material. Wear a wide brimmed hat. Wear SPF 30-50 depending on skin type and reapply every 2 hours. </p>
        </div>
    </div>

    <!-- Very High -->
    <div class="stage-row">
        <div class="image-collage-wrap">
            <img src="https://images.pexels.com/photos/3021601/pexels-photo-3021601.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/16060561/pexels-photo-16060561/free-photo-of-woman-in-hat-and-red-skirt-in-orchard-in-spring.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/20045023/pexels-photo-20045023/free-photo-of-young-woman-in-a-straw-hat-looking-in-the-mirror-sitting-on-a-picnic-blanket.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
        </div>
        <div class="text-section">
            <h4>Very High UV Index: 8-10</h4>
            <p>Very high UV levels that can lead to skin damage within 10 minutes of exposure. Cover all exposed skin with dense fabric and ensure wide brimmed hats and sunglasses are used. Wear SPF 30-50 depending on skin type and reapply every 2 hours.</p>
        </div>
    </div>

    <!-- Extreme -->
    <div class="stage-row">
        <div class="text-section">
            <h4>Extreme UV Index: 11+</h4>
            <p>Extreme UV levels that will burn fair skinned people in approximately 5 minutes. At this level of UV seek shade and try to stay indoors from 10am and 4pm. If going outside, cover all exposed skin with densely woven and dark coloured material. Wear wide brimmed hats. Wear SPF50+ sunscreen and reapply every 90 minutes. </p>
        </div>
        <div class="image-collage-row">
            <img src="https://images.pexels.com/photos/5530756/pexels-photo-5530756.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/16359892/pexels-photo-16359892/free-photo-of-back-view-of-man-in-cowboy-hat.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/7817686/pexels-photo-7817686.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
            <img src="https://images.pexels.com/photos/18140059/pexels-photo-18140059/free-photo-of-a-woman-standing-in-the-garden-with-a-sun-umbrella.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="Image for clothing section" />
        </div>
    </div>
</div>

<div style="text-align: center;">
    <a class="btn btn-outline-dark" href="/Home/SunscreenUsage" style="display: block; width: 100%; text-align: center; box-sizing: border-box;">Learn to Apply Sunscreen Properly »</a>
</div>

SunScreenApplication/Views/Home/FunSunSafety.cshtml
@{
	ViewBag.Title = "FunSunSafety";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<div id="FunsSunSafetyStart"></div>
<div class="portionheader">
	<h1>Sun Safety Fun and Engaging Activities for Children</h1>
</div>
<p>
	
Understanding age-appropriate, fun, and engaging ways to teach sun safety to children is crucial for fostering long-lasting, healthy habits. Early, tailored education in this area enhances learning and retention, especially given the heightened sensitivity of young skin to UV damage. By making sun protection practices enjoyable and relatable, children are more likely to engage willingly, reducing resistance to essential actions like applying sunscreen or wearing protective clothing. 
</p>

<!-- setup like a row by row format -->
<div class="uv-index-guide-vertical">

	<!-- conent organized horiontally -->
	<!-- Activity 1 -->
	<div class="stage-row" style="padding: 20px 0;">
		<div class="text-section">
			<h4>Sunscreen Reward Chart</h4>
			<p>Create a reward chart where children get stickers for every time they remember to wear sunscreen. Rewards can be given for a certain number of stickers.</p>
		</div>
		<div class="row-single-image">
			<img src="https://images.pexels.com/photos/7005760/pexels-photo-7005760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="image for activity" />
		</div>
	</div>

	<!-- Activity 2 -->
	<div class="stage-row" style="padding: 20px 0;">
		<div class="text-section">
			<h4>Color-Changing UV Beads</h4>
			<p>Use beads that change color in UV light to create bracelets or keychains. These serve as fun and visual reminders of the presence of UV radiation.</p>
		</div>
		<div class="row-single-image">
			<img src="https://images.pexels.com/photos/16129254/pexels-photo-16129254/free-photo-of-close-up-of-a-necklace-with-yellow-beads.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="image for activity" />
		</div>
	</div>

	<!-- Activity 3 -->
	<div class="stage-row" style="padding: 20px 0;">
		<div class="text-section">
			<h4>DIY Sun Protection Gear</h4>
			<p>Encourage older children to create their own sun-safe clothing or accessories, like decorating wide-brimmed hats.</p>
		</div>
		<div class="row-single-image">
			<img src="https://images.pexels.com/photos/7585857/pexels-photo-7585857.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="image for activity" />
		</div>
	</div>

	<!-- Activity 4 -->
	<div class="stage-row" style="padding: 20px 0;">
		<div class="text-section">
			<h4>Sun-Safe Gardening</h4>
			<p>Involve children in gardening activities, ensuring they wear sun-protective clothing. They can learn about sun safety while also learning about nature.</p>
		</div>
		<div class="row-single-image">
			<img src="https://images.pexels.com/photos/7782193/pexels-photo-7782193.jpeg" alt="image for activity" />
		</div>
	</div>

	<!-- Activity 5 -->
	<div class="stage-row" style="padding: 20px 0;">
		<div class="text-section">
			<h4>Sun Safety Story Time</h4>
			<p>Read books or create stories that include characters practicing sun safety. This can help children understand the importance of sun protection.</p>
		</div>
		<div class="row-single-image">
			<img src="https://images.pexels.com/photos/3755621/pexels-photo-3755621.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="image for activity" />
		</div>
	</div>
</div>

<br>
<br>

<div class="container">
	<div class="row">
		<div class="col-12 col-md-6">
			<a class="btn btn-outline-dark w-100 mb-2 mb-md-0" href="/Home/SunscreenUsage">Learn to Apply Sunscreen Properly »</a>
		</div>
		<div class="col-12 col-md-6">
			<a class="btn btn-outline-dark w-100" href="/Home/ClothingRecommendations">Go for Clothing Recommendations »</a>
		</div>
	</div>
</div>

SunScreenApplication/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
	<div class="banner">
		<div>
			<p>Empowering Australians with UV Awareness,</p>
			<p>Sun Protection Advice and</p>
			<p>Educational Resources</p>

			@Html.ActionLink("TRACK UV »", "Form", "UvIndex", null, new { @class = "btn btn-outline-dark-big" })
		</div>
	</div>
</div>

<div class="portionheader">
	<h1>What is UV and its Impacts?</h1>
	<p>
		Ultraviolet (UV) rays are responsible for more than 95% of skin cancers, yet many mistakenly
		associate them solely with sunlight and heat. It's important to note that UV rays are
		invisible and cannot be felt, leading to potential confusion.
	</p>
	<div>
		<h2>Benefits</h2>
		<p>
			The sun aids in the production of vitamin D, a crucial nutrient for human health.
			Vitamin D facilitates the absorption of calcium and phosphorus from food, supporting
			bone development. The World Health Organization (WHO) suggests 5 to 15 minutes of sun
			exposure 2 to 3 times weekly to maintain adequate levels of vitamin D.
		</p>
		<h2>Risks</h2>
		<p>
			Protective measures such as sunscreen and sunglasses can mitigate UV radiation exposure.
			Sunburn indicates short-term overexposure, while prolonged exposure can result in
			premature aging and skin cancer. Failure to shield the eyes from UV radiation may
			increase the risk of sight-threatening eye diseases. Overexposure to UV radiation poses
			significant health risks, including cancer. Skin cancer is prevalent in Australia, with
			basal cell and squamous cell carcinomas being the most common types. Typically, these
			cancers develop on areas like the head, face, neck, hands, and arms, which receive the
			highest UV exposure. Melanoma, the deadliest form of skin cancer, is often attributed
			to UV radiation exposure. While anyone can experience adverse health effects from UV
			radiation, certain factors increase susceptibility:
		</p>
		<ol>
			<li>Prolonged sun exposure or history of sunburn</li>
			<li>Light-colored skin, hair, and eyes</li>
			<li>Use of certain medications or cosmetics that heighten skin and eye sensitivity to UV</li>
			<li>Family history of skin cancer</li>
			<li>Age over 50</li>
		</ol>
		<p>(https://www.cdc.gov/nceh/features/uv-radiation-safety/index.html)</p>
	</div>
</div>

<div class="uv-index-guide-horizontal">
	<!-- Problem 1 -->
	<div class="stage-column">
		<img src="https://free-images.com/lg/9361/melanoma.jpg" alt="Image 1 for Very Low UV Index" class="roundedimage image-filter" />
		<div class="text-section-full">
			<h4>Increased Risk of Skin Cancer</h4>
			<p>Australia has one of the highest rates of skin cancer in the world, including melanoma and non-melanoma skin cancers. UV radiation is a major contributing factor to the development of these cancers.</p>
		</div>
	</div>
	<!-- Problem 2 -->
	<div class="stage-column">
		<img src="https://free-images.com/lg/11fe/sunburn_back.jpg" alt="Image 1 for Very Low UV Index" class="roundedimage image-filter">
		<div class="text-section-full">
			<h4>Sunburn</h4>
			<p>Even a single sunburn, especially in childhood, can significantly increase the risk of developing skin cancer later in life. Children's skin is more sensitive and burns more easily than adult skin.</p>
		</div>
	</div>
	<!-- Problem 3 -->
	<div class="stage-column">
		<img src="https://free-images.com/lg/a755/koli_bacteria_escherichia_coli.jpg" alt="Image 2 for Very Low UV Index" class="roundedimage image-filter">
		<div class="text-section-full">
			<h4>Immune System Supression</h4>
			<p>UV radiation can impact the immune system, potentially reducing its ability to fight off certain diseases, including skin cancers.</p>
		</div>
	</div>
</div>

<div class="uv-index-guide-vertical">
	<!-- Heat Trend -->
	<div class="stage-row">
		<div class="text-section">
			<h4>Sun Safety Activities for Children</h4>
			<p>UV radiation in Australia can be particularly intense due to factors such as its proximity to the equator and the thinning ozone layer in the Southern Hemisphere. This makes sun safety especially important for children, whose skin is more sensitive to UV damage. Find age-appropriate tips and tricks to make sun safety fun and engaging for children.</p>
			@Html.ActionLink("Fun Sun Safety »", "FunSunSafety", "Home", null, new { @class = "btn btn-outline-dark" })
		</div>
		<div class="row-single-image">
			<img src="https://www.csiro.au/-/media/OnA/Images/SOTC-2022/2-Temperature/SoTC_T01_v3.png" alt="Australia Heat Trend" />
		</div>
		<div class="text-section">
			<h4>Australia Heat Trend</h4>
			<p>The current heat trend in Australia is an upward trend with it sharply rising in the past decade. This is very concerning because it will be the children that will live further into the future thus it’s vital they learn to understand the risks and know how to protect themselves from the sun.</p>
		</div>
	</div>
</div>

 <div class="uv-index-guide-contact">
	 <section class="row" aria-labelledby="aspnetTitle">
	 </section>

	 <div class="row">
		 <section class="col-md-6" aria-labelledby="gettingStartedTitle">
			 <h2 id="gettingStartedTitle">Track UV Indexes</h2>
			 <p>
				 Check to see the UVI Indexes at different locations in Victoria!
			 </p>
			 @Html.ActionLink("Go to Track UV »", "Form", "UvIndex", null, new { @class = "btn btn-outline-dark" })
			 <br>
			 <br>
			 <br>
			 <br>
		 </section>
		 <section class="col-md-6" aria-labelledby="hostingTitle">
			 <h2 id="hostingTitle">Contact Us</h2>
			 <p>Phone: +61 XXXXXXXXX</p>
			 <p>Email: admin@gmail.com</p>
			 <p>Address: 22 Wellington Rd, Clayton VIC 3800</p>
		 </section>
	 </div>
 </div>
 

SunScreenApplication/Views/Home/SunscreenUsage.cshtml
@{
    ViewBag.Title = "SunscreenUsage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<div id="SunscreenUsageStart"></div>
<div class="portionheader">
    <h1>How much Sunscreen to Use?</h1>
</div>
<p>
    To ensure optimal protection, utilize broad-spectrum sunscreen with SPF 30 or higher,
    in conjunction with wearing a hat, sunglasses, protective clothing, and seeking shade.
    It's crucial to reapply sunscreen every 2 hours, or more frequently if swimming or
    perspiring heavily.
</p>

<!-- Setup in a column by column format -->
<div class="uv-index-guide-horizontal">
    <!-- SPF Guide -->
    <!-- Conent organized in a column format -->
    <div class="stage-column">
        <img src="https://images.pexels.com/photos/16690692/pexels-photo-16690692/free-photo-of-packaging-with-sunscreen-on-the-ground-on-the-beach.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Image" />

        <div class="text-section-full">
            <h4>SPF Guide</h4>
            <p>- For UV Index up to 10, use at least 30+ SPF </p>
            <p>- For UV Index 11+ Extreme, use at least 50+ SPF </p>
            <p>- Generally, its always safer to just use 50+ SPF </p>
        </div>
    </div>

    <!-- Where to Apply -->
    <div class="stage-column">
        <img src="https://images.pexels.com/photos/8396725/pexels-photo-8396725.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Image" />
        <div class="text-section-full">
            <h4>Where to Apply</h4>
            <p>The following amount of sunscreen Adults need to apply is an approximate only:</p>
            <p>- To any exposed skin </p>
            <p>- No sunscreen provides 100% protection so always use with a broad brimmed hat, sunglasses, covering clothing and shade. </p>
            <br>
        </div>
    </div>

    <!-- Sunscreen Amount -->
    <div class="stage-column">
        <img src="https://images.pexels.com/photos/5269654/pexels-photo-5269654.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Image" />
        <div class="text-section-full">
            <h4>Sunscreen Amount</h4>
            <p>The following amount of sunscreen Adults need to apply is an approximate only:</p>
            <p>Wearing:</p>
            <p>- T-shirt + Shorts: At least 3 teaspoons </p>
            <p>- Long Sleeve Shirt + Shorts: At least 2.5 teaspoons </p>
            <p>- T-shirt + Long Pants: At least 2 teaspoons </p>
            <p>- Long Sleeve Shirt + Long Pants: At least 1,5 teaspoons </p>
            <p>- Full Body Application: At least 7 teaspoons </p>
        </div>
    </div>
    <!-- When to Apply -->
    <div class="stage-column">
        <img src="https://free-images.com/lg/6670/time_take_time_cosmetics.jpg" alt="Image" />
        <div class="text-section-full">
            <h4>When to Apply</h4>
            <p>- Apply at least 20 minutes beforehand </p>
            <p>- Reapply every 2 hours and more frequently if swimming or active </p>
        </div>
    </div>
</div>

<div style="text-align: center;">
    <a class="btn btn-outline-dark" href="/Home/ClothingRecommendations" style="display: block; width: 100%; text-align: center; box-sizing: border-box;">Go for Clothing Recommendations »</a>
</div>

SunScreenApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <link href="~/css/StyleSheet.css" rel="stylesheet" />
     <title>@ViewData["Title"] - SunScreenApplication</title>
     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
     <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
     <link rel="stylesheet" href="~/SunScreenApplication.styles.css" asp-append-version="true" />
 </head>
 <body>
 <header>
     <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
         <div class="container-fluid">
             <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SunSafeAwareness</a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                     aria-expanded="false" aria-label="Toggle navigation">
                 <span class="navbar-toggler-icon"></span>
             </button>
             <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                 <ul class="navbar-nav flex-grow-1">
                     <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                     </li>
                     <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="UvIndex" asp-action="Form">UV Index</a>
                     </li>

                     <li class="nav-item dropdown">
                         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                             Sun Protection Solutions
                         </a>
                         <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                             <li><a class="dropdown-item" asp-controller="Home" asp-action="SunscreenUsage">Sunsceen Usage</a></li>
                             <li><a class="dropdown-item" asp-controller="Home" asp-action="ClothingRecommendations">Clothing Recommendations</a></li>
                         </ul>
                     </li>
                     <li class="nav-item">
                         <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="FunSunSafety">Fun Sun Safety</a>
                     </li>
                 </ul>
             </div>
         </div>
     </nav>
 </header>
 <div class="container">
     <main role="main" class="pb-3">
         @RenderBody()
     </main>
 </div>

 <footer class="border-top footer text-muted">
     <div class="container">
         &copy; 2024 - SunScreenApplication
     </div>
 </footer>
 <script src="~/lib/jquery/dist/jquery.min.js"></script>
 <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
 <script src="~/js/site.js" asp-append-version="true"></script>
 @await RenderSectionAsync("Scripts", required: false)
 </body>
 </html>
 